language: scala
scala:
  - 2.13.0-RC2
  - 2.12.8
  - 2.12.6
  - 2.11.12

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)