language: scala
scala:
  - 2.13.6

jdk:
  - openjdk8

script:
  - sbt clean coverage test coverageReport

branches:
  only:
    - master
    
after_success:
  - bash <(curl -s https://codecov.io/bash)